# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSRxStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSRxStudy
  pod 'RxSwift'

  target 'iOSRxStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSRxStudyUITests' do
    # Pods for testing
  end

end
